language: node_js
node_js:
- '12'
cache:
  yarn: true
env:
- LOG_LEVEL=warn
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: A84gccwnXRuuNyVx30BgpsRKxBqrqO+IbZOmFVkhQZCXX9IZtoXGkfz02eH6xoORuKxKGz5+HSRijovCZaXsl12rMBcEnTmfcdiG5p9YPSpUwQ4+1hDE5ky5T+tXt9qjD/nOCbRIlG77PCTpW18bvABmH2V/rriqWploGyDNVW76sXKT9PekTYjFZlioSUUvsw8PB0DE/lTedy7pIhOjjIXW3L19l27yQM831Zly5ccXyclk/mkYchXafWyGSANPzYLv1RQxwtOFwP6hie5kk1y1yGgAoedVhmnoPdMRjZucBSjr3ry+Ne0dn2+6oUSWqjV9/WED3LdEU8a9OiNu6SeW4GyXIk8WNuDk7kZZ3VKbzit+67cw+VqK4LWkn4GFNIax/vTVziFEKJNqA0n+vTDUgRGIAU5XlRXZCyRT529h5NfY9j1rSk6DXPXLRvwaJMHTLHhafaJXpY3f7+B67CxDBg9mxsNPwN13zbktON05VyGGEDpmC9aXsO+iXOjvhhCfgO5fPBS/vRf1SWcRgi+ip6P+xHO73J0mqpq8Aj1GZZBN6el5LSL0YamqtJfJwSllgtk/porG99Kj3RSpplBzmS7hFpRcKYEh7F0TL+rUIYXUUZEL0BJaSWfL19F99LQXzmY5J4wP7axN1oNVakPI/FY72EavVciosaj9CbE=
  app: mix-it-client
  on:
    repo: codenights/mix-it-client
