language: node_js
node_js:
- '12'
cache:
  yarn: true
jobs:
  include:
  - stage: Test
    name: Tests
    script: yarn test
  - stage: Deploy
    if: branch = master
    name: API
    script: yarn build
    deploy:
      provider: heroku
      cleanup: false
      api_key:
        secure: OCVKFBTqEv4WS6g8hhJFHQbmLShjEobQOKhfG6OSGD7LbUDOXv1sbeLiyuEYC8QhHSIdTBgE7O3yknLk2BY2OTQfzsuofF8BhWF0HleWzdRdsfogYGvkMsY+B1kfGVkKzHeq9mn5m6FWbVWARI0GaKMTSwF8pEfJMybR5EEf93zXk+Telf9l38URIpXaoQZ8P9o6tfF7IHRGHE4IpA8R6z8PASDmuSn1TtkNyDGIM7HLtZPFfMfDU7myNqzV5xNb5QA0u8DpJ2kGkCJZNTfGHNmySDdSv4MUJiwGCkxY3dzmSKQdBRgypG0RDuIbZlz7vJWhseoQwGSKinnnxFtHqCtZeRq4fPNdFHFSzfIC1CbAlUFeGSq651clP5+j6Xc7oVD5oTlt4SkSvpE1NnaY8Py+8+UHz4dIeHScYGaBF9stKnCAn5bVv/gD6iR7LT7SBR0s7KfVNvLivzONV6h4I6ttF0gFupAbD7Y/qJ26+0JMjcdKzSqtQyMOxheOP3dv2H9PfY9hRyBgQKpbMsNc/DGa8qITvz/CKbub1fCrMjpfqQ3TCayaG14gNglzC+Bzg+OstglIxDWEW4fg1f/Bf8P6GxbQX2xWq+CWHDu8mf+Ww+P1B7nqEwb4CAm/KoMdOB4X6kZX5SxG5YeOxe38smHoGOAj967hYoaHYAG/c/o=
      app: mix-it-back
      on:
        repo: codenights/mix-it-back
  - name: API reference
    if: branch = master
    install: yarn global add redoc-cli
    script:
    - redoc-cli bundle reference/mix-it-api.v1.yaml
    - mkdir public
    - mv redoc-static.html public/index.html
    deploy:
      provider: pages
      cleanup: false
      token:
        secure: DZi5mqQcb2aF3SyWiDWDajrWdIHr5L8+ZytU1lVaOhjR33E8Y4Aj9YLJs13c4SJiuMiw5o3IK7+UejDEvAxyd1uSLyfpgGnwZTpaDHJL/3wS72YCUElnstkj2J3X6Th9WJ2wYrZnw0cqTyPRG6DJ8z0zMduM/eXp+k4DKtghwLXxFXkxdHup7JwJxaISkddOiDh4iIEJN1DL0G4sSP7wU+7AZzrBtpBgxGGI9SQj+jrGEtLEXcmmJalOAwbG9xyaFz5ri1bU8fTLCNgt6MhVe6OCQGup062qPRKYk0fOrOikVIoZ97sZrUJ3ol5N8fQQtyiFEFbaU4WsqPEYx024AdENDJwFAMvH5FWAJzstEJ+K3BilRbH8oBjmhbKJlXnyid9eLnpN9JHusEwxyX7TrVHz5E0ikHjC5e2uRJb80IgcPvkxVggDn1NOpNsOqVvAIR7uyrMnwRnI9EyYklPfoFI5Xe4BZYq2f0d8TGVNruRx5/q1C2/3xsicer7ruWtgyP2XvD35PdqjT4hI9kdLH6J/E/q74/xyHKxMoQK8tFBB0eXKnhnABe7KNx9F7jDRitwdcGPQmw1NlXJAWYLiH+wTiORULix2vjMxvIT879inWkmq/XnMSFP2qCUneLrv/+vXjaVq8CZZxDJ5Fdx9RXJF3gXVwXXTyIepqP9JFdg=
      keep_history: true
      local_dir: public
      on:
        branch: docs-add-api-reference
