language: node_js
node_js:
- '12'
cache:
  yarn: true
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: "OCVKFBTqEv4WS6g8hhJFHQbmLShjEobQOKhfG6OSGD7LbUDOXv1sbeLiyuEYC8QhHSIdTBgE7O3yknLk2BY2OTQfzsuofF8BhWF0HleWzdRdsfogYGvkMsY+B1kfGVkKzHeq9mn5m6FWbVWARI0GaKMTSwF8pEfJMybR5EEf93zXk+Telf9l38URIpXaoQZ8P9o6tfF7IHRGHE4IpA8R6z8PASDmuSn1TtkNyDGIM7HLtZPFfMfDU7myNqzV5xNb5QA0u8DpJ2kGkCJZNTfGHNmySDdSv4MUJiwGCkxY3dzmSKQdBRgypG0RDuIbZlz7vJWhseoQwGSKinnnxFtHqCtZeRq4fPNdFHFSzfIC1CbAlUFeGSq651clP5+j6Xc7oVD5oTlt4SkSvpE1NnaY8Py+8+UHz4dIeHScYGaBF9stKnCAn5bVv/gD6iR7LT7SBR0s7KfVNvLivzONV6h4I6ttF0gFupAbD7Y/qJ26+0JMjcdKzSqtQyMOxheOP3dv2H9PfY9hRyBgQKpbMsNc/DGa8qITvz/CKbub1fCrMjpfqQ3TCayaG14gNglzC+Bzg+OstglIxDWEW4fg1f/Bf8P6GxbQX2xWq+CWHDu8mf+Ww+P1B7nqEwb4CAm/KoMdOB4X6kZX5SxG5YeOxe38smHoGOAj967hYoaHYAG/c/o="
  app: mix-it-back
  on:
    repo: codenights/mix-it-back
